(function() {var implementors = {};
implementors["xplm"] = ["impl&lt;D,&nbsp;A&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/data/struct.Owned.html' title='xplm::data::Owned'>Owned</a>&lt;D,&nbsp;A&gt;","impl&lt;D,&nbsp;A&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/data/struct.Shared.html' title='xplm::data::Shared'>Shared</a>&lt;D,&nbsp;A&gt;","impl&lt;O&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/command/struct.Command.html' title='xplm::command::Command'>Command</a>&lt;O&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/flight_loop/struct.FlightLoop.html' title='xplm::flight_loop::FlightLoop'>FlightLoop</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/terrain/struct.Probe.html' title='xplm::terrain::Probe'>Probe</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/ui/widget/struct.Base.html' title='xplm::ui::widget::Base'>Base</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='xplm/graphics/window/struct.Window.html' title='xplm::graphics::window::Window'>Window</a>",];implementors["linked_list"] = ["impl&lt;T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='linked_list/struct.LinkedList.html' title='linked_list::LinkedList'>LinkedList</a>&lt;T&gt;",];implementors["nanovg"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Drop.html' title='core::ops::Drop'>Drop</a> for <a class='struct' href='nanovg/struct.Context.html' title='nanovg::Context'>Context</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
